mode: disabled # for using wandb, set to "online" after adding your wandb credentials
experiment: null
tag: null
wandb_project: "neonatal"
wandb_entity: "TODO"
wandb_home: "TODO"

data_path: "TODO" # path to dataset
pickle_path: null
result_path: "TODO"

seed: null