self: nam
in_channels:
 - 1
 - 1
 - 1
 - 1
 - 1
 - 1

# Example sweep grid for NAM
# Large grids may take a lot of compute
hidden_channels:
  sweep_grid:
    g1:
      - 10
      - 10
      - 10
      - 10
      - 10
      - 10
    g2:
      - 20
      - 20
      - 20
      - 20
      - 20
      - 20
    g3:
      - 40
      - 40
      - 40
      - 40
      - 40
      - 40
    g4:
      - 80
      - 80
      - 80
      - 80
      - 80
      - 80
    g5:
      - 80
      - 80
      - 80
      - 80
      - 80
      - 80
kernel_size:
  sweep_grid:
    g1:
      - 17 
      - 17
      - 5
      - 17
      - 5
      - 5
    g2:
      - 35 
      - 35
      - 11
      - 35
      - 11
      - 11
    g3:
      - 71 
      - 71
      - 23
      - 71
      - 23
      - 23
    g4:
      - 17 
      - 17
      - 11
      - 17
      - 11
      - 11
    g5:
      - 17 
      - 17
      - 23
      - 17
      - 23
      - 23
    g6:
      - 35 
      - 35
      - 5
      - 35
      - 5
      - 5
    g7:
      - 35 
      - 35
      - 23
      - 35
      - 23
      - 23
    g8:
      - 71 
      - 71
      - 5
      - 71
      - 5
      - 5
    g9:
      - 71 
      - 71
      - 11
      - 71
      - 11
      - 11

